project:
  type: website
  output-dir: docs

website:
  title: "Eris Progress"
  navbar:
    - href: home.qmd
      text: Home
    - href: week1.qmd
      text: Week 1

format:
  html:
    theme: cosmo
    toc: true