---
title: "Progress report"
author: "Victoria Sjalim"
date: "2026-06-10"
format: html

---

# 10/06/2026 

## Data information
Input data:
- Complete genome assembly: obtain from Genbank (contains chromosome and plasmids)
- Shovill simulated: only the chromosome 
- The realfastq simulated: only the chromosome
- .mmi the genome pathway
- .gfa is the assembly graph

## Investigate the output file 
```{python}
import pyeris

# Run Eris with simulated data
eris -i data/contigs_shovill_simulated.gfa \
    -d data/IS.mmi \
    -o output/eris_output_simulated


# Run Eris for only the contigs of the complete genome assembly
eris -i data/contigs_complete_genome_assembly.gfa -d data/IS.mmi -o output/eris_output_complete_genome
```

Have error from previous code and give an interval errors. 
There is no intervals detected errors when running the code.

Try downloading UV

```{python}
# For the simulated data
uv run eris -i data/contigs_shovill_simulated.gfa \
    -d data/IS.mmi \
    -o output/eris_output_simulated

# For the complete genome assembly
uv run eris -i ../data/EC958_complete_genome.fasta \
    -d ../data/IS.mmi -o ../output/eris_output_complete \
    -q

mkdir -p output/complete_genome && mv output/eris_output_complete* output/complete_genome/
```

We succesfully run Eris for both the simulated data and the complete genome assembly. We can now investigate the output files.

The problem with the complete genome assembly:
- Since it contains plasmids, ERIS didn't run successfully. The complete genome has less columns compared to the simulated data.
- 

# Analysing the output files
```{python}
import pandas as pd
# Load the output files
simulated_df = pd.read_csv("../output/output_simulated/eris_output_simulated_report.tsv", sep="\t")
complete_df = pd.read_csv("../output/complete_genome/eris_output_complete_report.tsv", sep="\t")

# Check the dimension of each dataframe
print("Simulated data shape:", simulated_df.shape)
print("Complete genome assembly shape:", complete_df.shape)

# Group IS elements together and count the number of occurrences for each IS element in both datasets
simulated_counts = simulated_df.groupby("target")["target"].count()
complete_counts = complete_df.groupby("target")["target"].count()

print("Total simulated data IS element counts:", simulated_counts.count())
print("Total complete genome assembly IS element counts:", complete_counts.count())
```

There are only 4 IS found in the complete genome assembly, while there are 35 distinct IS found in the simulated data. This means Eris doesn't perform well on the complete genome assembly, likely due to the presence of plasmids. We can investigate the IS elements found in both datasets by printing out the target column. 

```{python}
# In case we want to investigate the IS elements found in the complete genome assembly, we can print out the target column
print("IS elements found in complete genome assembly:")
print(complete_counts)

print("IS elements found in simulated data:")
print(simulated_counts)
```