---
title: "Progress report week 2"
author: "Victoria Sjalim"
date: "2026-06-17"
execute: 
  freeze: auto
---

# Data validations

# Investigate the output file after fragmentation
```{python}
# Load the new output file after fragmentation
import pandas as pd
# complete fragemented
complete_fragmented_df = pd.read_csv("../result/complete_fragmented/eris_complete_fragmented_report.tsv", sep="\t")

# Complete
complete_df = pd.read_csv("../result/complete_genome/eris_output_complete_report.tsv", sep="\t")
complete_counts = complete_df.groupby("target")["target"].count() 

# Simulated
simulated_df = pd.read_csv("../result/output_simulated/eris_output_simulated_report.tsv", sep="\t")
simulated_counts = simulated_df.groupby("target")["target"].count()
```

Want to see how much number of IS elements are detected 

```{python}
# Check the dimension of the new dataframe after fragmentation  
print("Dimension of the new dataframe after fragmentation:", complete_fragmented_df.shape)
# Group IS elements together and count the number of occurrences for each IS element in the new dataframe
complete_fragmented_counts = complete_fragmented_df.groupby("target")["target"].count()
print("Total IS element counts in the new dataframe after fragmentation:", complete_fragmented_counts.count())
```

## If they are intersecting

```{python}
# Check if the IS elements found in the fragmented complete genome assembly are also found in the simulated
common_fragmented = set(complete_fragmented_counts.index) & set(simulated_counts.index)
print("Number of common IS elements found in both datasets after fragmentation:", len(common_fragmented))
print("IS elements found in both datasets after fragmentation:")
print(common_fragmented)

# Check the IS elements found in the fragmented complete genome assembly that are not found in the simulated data
unique_fragmented = set(complete_fragmented_counts.index) - set(simulated_counts.index)
print("Number of IS elements found in the fragmented complete genome assembly that are not found in the simulated data:", len(unique_fragmented))
print("IS elements found in the fragmented complete genome assembly that are not found in the simulated data:")
print(unique_fragmented)
```

There are 15 common IS found in the simulated and plasmid datasets

## Total disruption
```{python}

def calc_disruption(df):
    total = int((df['effect'] == 'DISRUPTED').sum())
    percentage = float(total / len(df) *100)
    return total, round(percentage, 3)

print("Total IS that is disrupted in complete genome:", calc_disruption(complete_df))
print("Total IS that is disrupted in fragmented genome:", calc_disruption(complete_fragmented_df))
print("Total IS that is disrupted in simulated genome:", calc_disruption(simulated_df))


```

## Summary
| Total IS | Complete | Simulated | Fragmented |
|---------|:-----|------:|:------:|
| Total rows | 37 | 293 | 212 |
| Total disruption | 7 | 24 | 16 |
| Total unique IS | 4 | 35 | 24 |

: Demonstration of pipe table syntax

# Do the precision and recall calculations for the fragmented genome assembly

I have confusion how to calculate the precision and recall.

In the .bed file provided from Genbank, there are multiple IS with unique identifiers. We need to ensure we predicted the right IS element. 

We group the IS elements and count the number of occurrences for each IS element in the new dataframe. We also want to separate the name as well to identify the location.

```{python}
# obtain the first IS name
complete_fragmented_counts = complete_fragmented_df.groupby("target")["target"].count().reset_index(name="count")

complete_fragmented_counts["Name"] = complete_fragmented_counts['target'].str.split('_').str[0]

# Make it as a new variables (a bit too long)
clean_frag = complete_fragmented_counts
```

## Reading the BED file
Notice the position is so different. Since we want to intersect with the bed file, we want to have the original position back from the complete sequence

```{python}
# Reading the bed file
bed_columns = ['transcript', 'chromStart', 'chromEnd', 'name', 'score', 'strand']

# Read the file (use only the names that match your file's column count)
ann_bed = pd.read_table('../../data/complete_ec958_IS.reanotated.sorted.bed', header=None, names=bed_columns[:6])

print(ann_bed) 
```

## Calculate it based on the names
```{python}
# Make a list for the name only and separate the underscore 
# We remove any types in different position
ref_list = list(ann_bed["name"].str.split('_').str[0].drop_duplicates())

print(f'Total IS found in the list{len(ref_list)}')
print(ref_list)

ref_set = set(ref_list)

# Flag each row whether it's found or not
clean_frag['correct'] = clean_frag['Name'].isin(ref_set)

# Overall accuracy
accuracy_frag = clean_frag['correct'].mean()
print(f'Accuracy is {accuracy_frag:.2%}')

# Names not predicted in the list
wrong_frag = clean_frag.loc[~clean_frag['correct'], 'Name'].unique()
print("Names not found in reference list:", wrong_frag)

```



# Meeting Updates - 17/6/26
Our goals:
1. Do the precision recall from the complete genome sequence with the ground truth file
2. Determine whether the right position were called by Eris, especially for the chromosome (after the assembly)
3. Whether the context are correctly reported 

What we can do now?
1. Debug the minimap, especially how it behaving in the Fasta file
2. Add some pytest to see whether the code behaving like it should be
3. Investigate more about the IS15 (search the sequences and do BLAST search)

Notes:
- IS15 = IS26
- ISEcp1 = IS9

# Analysing the IS26/IS15

## Extracting the locations of the IS26 from the ground truth
```{python}
# Find the sequence for IS26 in the ground truth file
print(ann_bed[ann_bed['name'].str.startswith('IS26')])
# We do have 8 IS26 

is26_data = ann_bed[ann_bed['name'].str.startswith('IS26')]

# Save the new file as bedfile
is26_data[bed_columns].to_csv("../../data/IS26_data.bed", sep='\t', header=False, index=False)
```

Use bedtools to get the fasta
```{bash}
# bedtools getfasta -fi ../data/EC958_complete_genome.fasta -bed ./../data/IS26_data.bed -s -name > ./../progress/result/is26_hits.fa
```

Blast search

## Analysing IS15
```{python}
# Extract only the rows with IS15 on it
is15_df = complete_fragmented_df[complete_fragmented_df['target'].str.startswith("IS15")]
is15_df = is15_df.copy()

parts = is15_df['gene_id'].str.split('_')

# Extract the location
is15_df['transcript'] = parts.str[0:3].str.join('_')
is15_df['start'] = parts.str[3]
is15_df['end'] = parts.str[4]
is15_df['score'] = 0
is15_df['name'] = is15_df['target'].str.split('_').str[0]
# Map the strand
is15_df['strand'] = is15_df['orientation'].map({'same strand': '+', 'opposite strand': '-'})

print(is15_df.head(10))

# Create new bedfile
is15_bed = is15_df[['transcript', 'start', 'end', 'name','score', 'strand']]
is15_bed.to_csv('../../data/IS15_data.bed', sep="\t", header=False, index=False)
```

```{bash}
# bedtools getfasta -fi ../data/EC958_complete_genome_fragmented.fasta -bed ./../data/IS15_data.bed -s -name > ../progress/result/is15_hits.fa
```

## Analysing both datasets
```{python}
print("The dimension for the IS15", is15_bed.shape)
print("This is the data for IS15:")
!cat ../../data/IS15_data.bed

print("\nThe dimension for IS26:", is26_data.shape)
print("This is the data for the IS26")
!cat ../../data/IS26_data.bed
```

As we can see, it comes from the same transcript. However, more IS found for IS15 compared to ground truth.

Intersecting the file to see if they are actually the same sequence
```{bash}
# makeblastdb -in result/is_found/is26_hits.fa -dbtype nucl
# blastn -query result/is_found/is15_hits.fa -db result/is_found/is26_hits.fa -outfmt "6 qseqid sseqid pident length evalue" -out result/is_found/hits_disc
```


```{bash}
cat /../result/is_found/hits_disc | head -10
```

Several positions with IS26 (1, 3, 4, 5, 6, 7, 8) were similar with the IS15, IS15DI, and IS15DII. 
